SRCS += 
SRCS += sources/ft_already_sort.c
SRCS += sources/ft_check_error.c
SRCS += sources/ft_push.c
SRCS += sources/ft_push_first_n.c
SRCS += sources/ft_ranking.c
SRCS += sources/ft_rev_rotate.c
SRCS += sources/ft_rotate.c
SRCS += sources/ft_stack_creation.c
SRCS += sources/ft_swap.c
SRCS += sources/link_list_core.c
SRCS += sources/push_swap.c
SRCS += sources/push_swap_100.c
SRCS += sources/push_swap_3.c
SRCS += sources/push_swap_5.c
